In [119]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mlp

In [120]:
review_row = pd.read_csv('Category_Gusuk_Review_Final - 네이버리뷰.csv', encoding='cp949')
review = review_row.copy()
review=review[["Attraction",	"Good_Point",	"Selected_People"]]
review.head()

  Attraction    Good_Point  Selected_People
0  동대문역사문화공원        뷰가 좋아요             22.0
1  동대문역사문화공원   관리가 잘 되어있어요             21.0
2  동대문역사문화공원      볼거리가 많아요             14.0
3  동대문역사문화공원     사진이 잘 나와요             12.0
4  동대문역사문화공원  산책로가 잘 되어있어요             12.0

In [121]:
category_row = pd.read_csv('Category_Gusuk_Review_Final - 카테고리_구석.csv', encoding='cp949')
category = category_row.copy()
category=category[["Attraction","Category",	"Address","Participants"]]
category.head()

  Attraction Category                   Address Participants
0  동대문역사문화공원       관광          서울특별시 중구 신당동 853           56
1      서울식물원       관광  서울특별시 강서구 마곡동로 161 서울식물원        5,204
2      N서울타워       관광       서울특별시 용산구 남산공원길 105        5,100
3        서울숲       관광         서울특별시 성동구 뚝섬로 273          258
4        경복궁       관광     서울특별시 종로구 사직로 161 경복궁        1,202

In [122]:
total_info = pd.merge(review, category, on = 'Attraction', how = 'inner')
total_info = total_info[total_info['Category'].isin(['관광', '음식'])]

In [123]:
total_info['Attraction'].nunique()

804

In [124]:
total_info[total_info['Category'] == '음식']['Attraction'].nunique()

451

In [125]:
type_food_row = pd.read_csv('food_type_final_v2.csv', encoding='cp949')
type_food = type_food_row.copy()
type_food = type_food[['Attraction','type']]
type_food

                   Attraction      type
0                         채그로      cafe
1                      소소한 풍경    korean
2                     마복림할머니집    korean
3                   뮤직컴플렉스 서울      cafe
4                       또순이네집    korean
..                        ...       ...
445                   해담채 삼성점    korean
446             까사빠보 신세계백화점본점  japanese
447  포포인츠 바이 쉐라톤 조선 서울역 더 이터리       etc
448               오양회참치 광화문본점    korean
449                      h450      west

[450 rows x 2 columns]

In [126]:
for word in type_food['Attraction']:
    if word in total_info['Attraction'].tolist():
        continue
    else:
        print(word)

In [127]:
type_food

                   Attraction      type
0                         채그로      cafe
1                      소소한 풍경    korean
2                     마복림할머니집    korean
3                   뮤직컴플렉스 서울      cafe
4                       또순이네집    korean
..                        ...       ...
445                   해담채 삼성점    korean
446             까사빠보 신세계백화점본점  japanese
447  포포인츠 바이 쉐라톤 조선 서울역 더 이터리       etc
448               오양회참치 광화문본점    korean
449                      h450      west

[450 rows x 2 columns]

In [128]:
info_food = pd.merge(type_food, total_info, on='Attraction', how='inner')
info_food
# 10500

,Attraction,type,Good_Point,Selected_People,Category,Address,Participants
0,채그로,cafe,뷰가 좋아요,146.0,음식,서울특별시 마포구 마포대로4다길 31,201
1,채그로,cafe,집중하기 좋아요,62.0,음식,서울특별시 마포구 마포대로4다길 31,201
2,채그로,cafe,읽을만한 책이 많아요,61.0,음식,서울특별시 마포구 마포대로4다길 31,201
3,채그로,cafe,인테리어가 멋져요,60.0,음식,서울특별시 마포구 마포대로4다길 31,201
4,채그로,cafe,커피가 맛있어요,39.0,음식,서울특별시 마포구 마포대로4다길 31,201
...,...,...,...,...,...,...,...
10528,h450,west,아늑해요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260
10529,h450,west,메뉴 구성이 알차요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260
10530,h450,west,건강한 맛이에요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260
10531,h450,west,음료가 맛있어요,1.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260
10532,h450,west,음식이 빨리 나와요,1.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260

In [129]:
info_food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10533 entries, 0 to 10532
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Attraction       10533 non-null  object
 1   type             10533 non-null  object
 2   Good_Point       10533 non-null  object
 3   Selected_People  10533 non-null  float64
 4   Category         10533 non-null  object
 5   Address          10533 non-null  object
 6   Participants     10533 non-null  object
dtypes: float64(1), object(6)
memory usage: 576.2+ KB

In [130]:
info_food['Attraction'].nunique()

450

In [131]:
duplicates = info_food[info_food.duplicated()]
duplicates

Empty DataFrame
Columns: [Attraction, type, Good_Point, Selected_People, Category, Address, Participants]
Index: []

In [132]:
category_map_food = {
    "시설 및 분위기": ["뷰가 좋아요", "인테리어가 멋져요", "사진이 잘 나와요", "경관이 독특해요",
                    "좌석이 편해요", "매장이 넓어요", "룸이 잘 되어있어요", "야외 공간이 멋져요",
                    "산책로가 잘 되어있어요", "피크닉하기 좋아요", "편의시설이 잘 되어있어요", "공간이 넓어요",
                    "붐비지 않아요", "방문객이 많아요",
                    "특별한 날 가기 좋아요", "컨셉이 독특해요", "테마가 재미있어요", "아늑해요",
                    "차분한 분위기에요", "오래 머무르기 좋아요", "조용히 쉬기 좋아요", "혼밥하기 좋아요", "혼술하기 좋아요",
                    "파티하기 좋아요", "라이브공연이 훌륭해요", "음악이 좋아요", "대화하기 좋아요", "집중하기 좋아요",
                    "화장실이 깨끗해요", "매장이 청결해요", "환기가 잘 돼요", "관리가 잘 되어있어요",
                    "단체모임 하기 좋아요", "아이와 가기 좋아요", "부모도 쉬기 좋아요", "읽을만한 책이 많아요",
                    "볼거리가 많아요", "반려동물과 가기 좋아요", "선물하기 좋아요",
                    "놀거리가 많아요", "체험 프로그램이 많아요",
                    "대중교통이 편해요", "근처에 갈 곳이 많아요", "주차하기 편해요" ],

    "음식의 속성": ["커피가 맛있어요", "음료가 맛있어요", "디저트가 맛있어요", "차가 맛있어요",
                    "재료가 신선해요", "건강한 맛이에요", "신선해요", "원산지 표시가 명확해요",
                    "음식이 맛있어요", "양이 많아요", "고기 질이 좋아요", "잡내가 적어요", "빵이 맛있어요", "기본 안주가 좋아요",
                    "특별한 메뉴가 있어요", "반찬이 잘 나와요", "술이 다양해요",
                    "코스가 길어요", "먹거리가 풍부해요", "샐러드바가 잘 되어있어요", "부위가 다양해요", "종류가 다양해요",
                    "향신료가 강하지 않아요","현지 맛에 가까워요"],

    "가격 및 가치": ["가성비가 좋아요", "코스요리가 알차요", "세트 구성이 알차요", "비싼 만큼 가치있어요",
                     "가격이 합리적이에요", "메뉴 구성이 알차요"],

    "서비스" : ["친절해요", "음식이 빨리 나와요", "포장이 깔끔해요", "직접 잘 구워줘요", "주문제작을 잘해줘요", 
             "안전하게 관리해요", "비주얼이 좋아요"],

}

In [133]:
info_food = info_food[info_food['Category'] == '음식']

# df에 속성을 업로
def update_categories(info_food, category_map_food):
    for category, keywords in category_map_food.items():
        for keyword in keywords:
            info_food.loc[info_food['Good_Point'].str.contains(keyword), 'Category_Map'] = category
    return info_food

info_food = update_categories(info_food, category_map_food)
info_food

,Attraction,type,Good_Point,Selected_People,Category,Address,Participants,Category_Map
0,채그로,cafe,뷰가 좋아요,146.0,음식,서울특별시 마포구 마포대로4다길 31,201,시설 및 분위기
1,채그로,cafe,집중하기 좋아요,62.0,음식,서울특별시 마포구 마포대로4다길 31,201,시설 및 분위기
2,채그로,cafe,읽을만한 책이 많아요,61.0,음식,서울특별시 마포구 마포대로4다길 31,201,시설 및 분위기
3,채그로,cafe,인테리어가 멋져요,60.0,음식,서울특별시 마포구 마포대로4다길 31,201,시설 및 분위기
4,채그로,cafe,커피가 맛있어요,39.0,음식,서울특별시 마포구 마포대로4다길 31,201,음식의 속성
...,...,...,...,...,...,...,...,...
10528,h450,west,아늑해요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,시설 및 분위기
10529,h450,west,메뉴 구성이 알차요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,가격 및 가치
10530,h450,west,건강한 맛이에요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,음식의 속성
10531,h450,west,음료가 맛있어요,1.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,음식의 속성
10532,h450,west,음식이 빨리 나와요,1.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,서비스

In [134]:
category_map_food_v2 = {
    # 시설 및 분위기
    "시설 및 환경": ["뷰가 좋아요", "인테리어가 멋져요", "사진이 잘 나와요", "경관이 독특해요",
                    "좌석이 편해요", "매장이 넓어요", "룸이 잘 되어있어요", "야외 공간이 멋져요",
                    "주차하기 편해요", "산책로가 잘 되어있어요", "피크닉하기 좋아요", "편의시설이 잘 되어있어요", "공간이 넓어요",
                    "붐비지 않아요", "방문객이 많아요"],
    
    "분위기": ["특별한 날 가기 좋아요", "컨셉이 독특해요", "테마가 재미있어요", "아늑해요", 
              "차분한 분위기에요", "오래 머무르기 좋아요", "조용히 쉬기 좋아요", "혼밥하기 좋아요", "혼술하기 좋아요", 
              "파티하기 좋아요", "라이브공연이 훌륭해요", "음악이 좋아요", "대화하기 좋아요", "집중하기 좋아요"],
   
    "청결도와 위생":  ["화장실이 깨끗해요", "매장이 청결해요", "환기가 잘 돼요", "관리가 잘 되어있어요"],

    "접근성": ["대중교통이 편해요", "근처에 갈 곳이 많아요"],
    
    "특별한 목적": ["단체모임 하기 좋아요", "아이와 가기 좋아요", "부모도 쉬기 좋아요", "읽을만한 책이 많아요", 
                   "현지 맛에 가까워요", "볼거리가 많아요", "반려동물과 가기 좋아요", "선물하기 좋아요", 
                   "비주얼이 좋아요", "놀거리가 많아요", "체험 프로그램이 많아요"],
        
    # 음식의 속성
    "음식의 맛과 질": ["커피가 맛있어요", "음료가 맛있어요", "디저트가 맛있어요", "차가 맛있어요","향신료가 강하지 않아요",
                      "재료가 신선해요", "건강한 맛이에요", "신선해요", "원산지 표시가 명확해요", '현지 맛에 가까워요',
                      "음식이 맛있어요", "양이 많아요", "고기 질이 좋아요", "잡내가 적어요", "빵이 맛있어요", "기본 안주가 좋아요"],

    "음식의 다양성": ["특별한 메뉴가 있어요", "반찬이 잘 나와요", "술이 다양해요",
                     "코스가 길어요", "먹거리가 풍부해요", "샐러드바가 잘 되어있어요", "부위가 다양해요", "종류가 다양해요"],   
    
    # 서비스
    "서비스" : ["친절해요", "음식이 빨리 나와요", "포장이 깔끔해요", "직접 잘 구워줘요", 
             "주문제작을 잘해줘요", "안전하게 관리해요", '비주얼이 좋아요'],
    
    # 가격 및 가치
    "가격과 가치": ["가성비가 좋아요", "코스요리가 알차요", "메뉴 구성이 알차요", 
               "세트 구성이 알차요", "비싼 만큼 가치있어요", "가격이 합리적이에요"]

}

In [135]:
info_food = info_food[info_food['Category'] == '음식']

# df에 속성을 업로
def update_categories(info_food, category_map_food_v2):
    for category, keywords in category_map_food_v2.items():
        for keyword in keywords:
            info_food.loc[info_food['Good_Point'].str.contains(keyword), 'Category_Map_v2'] = category
    return info_food

info_food = update_categories(info_food, category_map_food_v2)
info_food

,Attraction,type,Good_Point,Selected_People,Category,Address,Participants,Category_Map,Category_Map_v2
0,채그로,cafe,뷰가 좋아요,146.0,음식,서울특별시 마포구 마포대로4다길 31,201,시설 및 분위기,시설 및 환경
1,채그로,cafe,집중하기 좋아요,62.0,음식,서울특별시 마포구 마포대로4다길 31,201,시설 및 분위기,분위기
2,채그로,cafe,읽을만한 책이 많아요,61.0,음식,서울특별시 마포구 마포대로4다길 31,201,시설 및 분위기,특별한 목적
3,채그로,cafe,인테리어가 멋져요,60.0,음식,서울특별시 마포구 마포대로4다길 31,201,시설 및 분위기,시설 및 환경
4,채그로,cafe,커피가 맛있어요,39.0,음식,서울특별시 마포구 마포대로4다길 31,201,음식의 속성,음식의 맛과 질
...,...,...,...,...,...,...,...,...,...
10528,h450,west,아늑해요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,시설 및 분위기,분위기
10529,h450,west,메뉴 구성이 알차요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,가격 및 가치,가격과 가치
10530,h450,west,건강한 맛이에요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,음식의 속성,음식의 맛과 질
10531,h450,west,음료가 맛있어요,1.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,음식의 속성,음식의 맛과 질
10532,h450,west,음식이 빨리 나와요,1.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,서비스,서비스

In [136]:
info_food.columns

Index(['Attraction', 'type', 'Good_Point', 'Selected_People', 'Category',
       'Address', 'Participants', 'Category_Map', 'Category_Map_v2'],
      dtype='object')

In [137]:
info_food=info_food[['Attraction', 'Category', 'type', "Category_Map",'Category_Map_v2', "Good_Point", "Selected_People", "Participants"]]

In [138]:
info_food['Attraction'].nunique()

450

In [139]:
info_food

,Attraction,Category,type,Category_Map,Category_Map_v2,Good_Point,Selected_People,Participants
0,채그로,음식,cafe,시설 및 분위기,시설 및 환경,뷰가 좋아요,146.0,201
1,채그로,음식,cafe,시설 및 분위기,분위기,집중하기 좋아요,62.0,201
2,채그로,음식,cafe,시설 및 분위기,특별한 목적,읽을만한 책이 많아요,61.0,201
3,채그로,음식,cafe,시설 및 분위기,시설 및 환경,인테리어가 멋져요,60.0,201
4,채그로,음식,cafe,음식의 속성,음식의 맛과 질,커피가 맛있어요,39.0,201
...,...,...,...,...,...,...,...,...
10528,h450,음식,west,시설 및 분위기,분위기,아늑해요,2.0,260
10529,h450,음식,west,가격 및 가치,가격과 가치,메뉴 구성이 알차요,2.0,260
10530,h450,음식,west,음식의 속성,음식의 맛과 질,건강한 맛이에요,2.0,260
10531,h450,음식,west,음식의 속성,음식의 맛과 질,음료가 맛있어요,1.0,260
10532,h450,음식,west,서비스,서비스,음식이 빨리 나와요,1.0,260

In [140]:
info_food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10533 entries, 0 to 10532
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Attraction       10533 non-null  object
 1   Category         10533 non-null  object
 2   type             10533 non-null  object
 3   Category_Map     10533 non-null  object
 4   Category_Map_v2  10533 non-null  object
 5   Good_Point       10533 non-null  object
 6   Selected_People  10533 non-null  float64
 7   Participants     10533 non-null  object
dtypes: float64(1), object(7)
memory usage: 658.4+ KB

In [141]:
info_food.to_csv('dataset_food.csv')