In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mlp

In [77]:
review_row = pd.read_csv('category_Gusuk_Review_Final - 네이버리뷰.csv')
review = review_row.copy()
review=review[["Attraction",	"Good_Point",	"Selected_People"]]
review.head()

  Attraction    Good_Point  Selected_People
0  동대문역사문화공원        뷰가 좋아요             22.0
1  동대문역사문화공원   관리가 잘 되어있어요             21.0
2  동대문역사문화공원      볼거리가 많아요             14.0
3  동대문역사문화공원     사진이 잘 나와요             12.0
4  동대문역사문화공원  산책로가 잘 되어있어요             12.0

In [78]:
category_row = pd.read_csv('Category_Gusuk_Review_Final - 카테고리_구석.csv')
category = category_row.copy()
category=category[["Attraction","Category",	"Address","Participants"]]
category.head()

  Attraction Category                   Address Participants
0  동대문역사문화공원       관광          서울특별시 중구 신당동 853           56
1      서울식물원       관광  서울특별시 강서구 마곡동로 161 서울식물원        5,204
2      N서울타워       관광       서울특별시 용산구 남산공원길 105        5,100
3        서울숲       관광         서울특별시 성동구 뚝섬로 273          258
4        경복궁       관광     서울특별시 종로구 사직로 161 경복궁        1,202

In [79]:
total_info = pd.merge(review, category, on = 'Attraction', how = 'inner')
total_info = total_info[total_info['Category'].isin(['관광', '음식'])]

In [80]:
total_info['Attraction'].nunique()

802

In [81]:
type_food_row = pd.read_csv('food_type_v2.csv')
type_food = type_food_row.copy()
type_food = type_food[['Attraction','type']]
type_food.head()

  Attraction    type
0        채그로    cafe
1     소소한 풍경  korean
2    마복림할머니집  korean
3  뮤직컴플렉스 서울    cafe
4      또순이네집  korean

In [82]:
type_tour_row = pd.read_csv('tour_type_v3.csv')
type_tour = type_tour_row.copy()
type_tour.columns

Index(['Unnamed: 0', 'Attraction', 'tag_word_N', 'nature', 'history',
       'experience', 'theme', 'culture', 'shop_etc', 'max', 'type',
       '성원님 수정 type', '수정type 3', '비교군', '비교군.1', 'subclass', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21'],
      dtype='object')

In [83]:
type_tour = type_tour[['Attraction','수정type 3']]
type_tour.rename(columns = {'수정type 3':'type'}, inplace=True)
type_tour.head()

     Attraction      type
0      104고지전적비   history
1   10꼬르소꼬모 청담점  shop_etc
2          63아트   culture
3  가락농수산물종합도매시장  shop_etc
4           가락몰  shop_etc

In [84]:
type = pd.concat([type_tour, type_food], axis=0)
type

                   Attraction      type
0                    104고지전적비   history
1                 10꼬르소꼬모 청담점  shop_etc
2                        63아트   culture
3                가락농수산물종합도매시장  shop_etc
4                         가락몰  shop_etc
..                        ...       ...
446                   해담채 삼성점    korean
447                      까사빠보  japanese
448  포포인츠 바이 쉐라톤 조선 서울역 더 이터리       etc
449               오양회참치 광화문본점    korean
450                      h450      west

[788 rows x 2 columns]

In [85]:
info = pd.merge(type, total_info, on='Attraction', how='inner')
info

,Attraction,type,Good_Point,Selected_People,Category,Address,Participants
0,104고지전적비,history,사진이 잘 나와요,91.0,관광,서울특별시 서대문구 연희동 산100-1,203
1,104고지전적비,history,볼거리가 많아요,58.0,관광,서울특별시 서대문구 연희동 산100-1,203
2,104고지전적비,history,붐비지 않아요,40.0,관광,서울특별시 서대문구 연희동 산100-1,203
3,104고지전적비,history,가격이 합리적이에요,37.0,관광,서울특별시 서대문구 연희동 산100-1,203
4,104고지전적비,history,관리가 잘 되어있어요,31.0,관광,서울특별시 서대문구 연희동 산100-1,203
...,...,...,...,...,...,...,...
15517,h450,west,아늑해요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260
15518,h450,west,메뉴 구성이 알차요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260
15519,h450,west,건강한 맛이에요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260
15520,h450,west,음료가 맛있어요,1.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260
15521,h450,west,음식이 빨리 나와요,1.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260

In [86]:
info['Attraction'].nunique()

785

In [87]:
category_map_food = {
    "시설 및 분위기": ["뷰가 좋아요", "인테리어가 멋져요", "사진이 잘 나와요", "경관이 독특해요",
                    "좌석이 편해요", "매장이 넓어요", "룸이 잘 되어있어요", "야외 공간이 멋져요",
                    "산책로가 잘 되어있어요", "피크닉하기 좋아요", "편의시설이 잘 되어있어요", "공간이 넓어요",
                    "붐비지 않아요", "방문객이 많아요",
                    "특별한 날 가기 좋아요", "컨셉이 독특해요", "테마가 재미있어요", "아늑해요",
                    "차분한 분위기에요", "오래 머무르기 좋아요", "조용히 쉬기 좋아요", "혼밥하기 좋아요", "혼술하기 좋아요",
                    "파티하기 좋아요", "라이브공연이 훌륭해요", "음악이 좋아요", "대화하기 좋아요", "집중하기 좋아요",
                    "화장실이 깨끗해요", "매장이 청결해요", "환기가 잘 돼요", "관리가 잘 되어있어요",
                    "단체모임 하기 좋아요", "아이와 가기 좋아요", "부모도 쉬기 좋아요", "읽을만한 책이 많아요",
                    "볼거리가 많아요", "반려동물과 가기 좋아요", "선물하기 좋아요",
                    "놀거리가 많아요", "체험 프로그램이 많아요",
                    "대중교통이 편해요", "근처에 갈 곳이 많아요", "주차하기 편해요" ],

    "음식의 속성": ["커피가 맛있어요", "음료가 맛있어요", "디저트가 맛있어요", "차가 맛있어요",
                    "재료가 신선해요", "건강한 맛이에요", "신선해요", "원산지 표시가 명확해요",
                    "음식이 맛있어요", "양이 많아요", "고기 질이 좋아요", "잡내가 적어요", "빵이 맛있어요", "기본 안주가 좋아요",
                    "특별한 메뉴가 있어요", "반찬이 잘 나와요", "술이 다양해요",
                    "코스가 길어요", "먹거리가 풍부해요", "샐러드바가 잘 되어있어요", "부위가 다양해요", "종류가 다양해요",
                    "향신료가 강하지 않아요","현지 맛에 가까워요", "비주얼이 좋아요"],

    "가격 및 가치": ["가성비가 좋아요", "코스요리가 알차요", "세트 구성이 알차요", "비싼 만큼 가치있어요",
                     "가격이 합리적이에요", "메뉴 구성이 알차요"],

    "서비스" : ["친절해요", "음식이 빨리 나와요", "포장이 깔끔해요", "직접 잘 구워줘요", "주문제작을 잘해줘요", "안전하게 관리해요"],

}

In [88]:
info_food = info[info['Category'] == '음식']

# df에 속성을 업로
def update_categories(info_food, category_map_food):
    for category, keywords in category_map_food.items():
        for keyword in keywords:
            info_food.loc[info_food['Good_Point'].str.contains(keyword), 'Category_Map'] = category
    return info_food

info_food = update_categories(info_food, category_map_food)
info_food

C:\Users\82108\AppData\Local\Temp\ipykernel_25996\3725793645.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  info_food.loc[info_food['Good_Point'].str.contains(keyword), 'Category_Map'] = category

,Attraction,type,Good_Point,Selected_People,Category,Address,Participants,Category_Map
4851,채그로,cafe,뷰가 좋아요,146.0,음식,서울특별시 마포구 마포대로4다길 31,201,시설 및 분위기
4852,채그로,cafe,집중하기 좋아요,62.0,음식,서울특별시 마포구 마포대로4다길 31,201,시설 및 분위기
4853,채그로,cafe,읽을만한 책이 많아요,61.0,음식,서울특별시 마포구 마포대로4다길 31,201,시설 및 분위기
4854,채그로,cafe,인테리어가 멋져요,60.0,음식,서울특별시 마포구 마포대로4다길 31,201,시설 및 분위기
4855,채그로,cafe,커피가 맛있어요,39.0,음식,서울특별시 마포구 마포대로4다길 31,201,음식의 속성
...,...,...,...,...,...,...,...,...
15517,h450,west,아늑해요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,시설 및 분위기
15518,h450,west,메뉴 구성이 알차요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,가격 및 가치
15519,h450,west,건강한 맛이에요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,음식의 속성
15520,h450,west,음료가 맛있어요,1.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,음식의 속성
15521,h450,west,음식이 빨리 나와요,1.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,서비스

In [89]:
#시설 및 분위기(인테리어 청결 규모 시설에 대한 구성) / 편의성(접근성,위치) / 활동(프로그램) / 서비스 / 가격(문화나 쇼핑)
category_map_tour = {
"시설 및 분위기" : ["관리가 잘 되어있어요", "화장실이 깨끗해요", "샤워실이 잘 되어있어요", "숙박하기 좋아요", "시설이 깔끔해요", "온수가 잘 나와요", "공용시설 관리가 잘돼요", "부대시설이 잘 되어있어요",
"매너타임이 잘 지켜져요", "개수대가 잘 되어있어요", "냉난방이 잘돼요", "취사시설이 잘 되어있어요", "방음이 잘돼요", "침구가 좋아요", "보안시설이 잘 되어있어요", "대여장비 상태가 좋아요",
"휴게공간이 잘 되어있어요", "대기공간이 잘 되어있어요", "전기 사용이 편해요", "기구가 청결해요", "반납이 편해요", "취식 공간이 잘 되어있어요", "파우더룸이 잘 되어있어요", "연습공간이 잘 되어있어요",
"수면실이 잘 되어있어요", "노천탕이 잘 되어있어요", "탕이 넓어요", "수질 관리가 잘돼요", "사이트 간격이 넓어요", "벌레 걱정 없어요", "화장실이 잘 되어있어요", "규모가 커요", "반려동물과 가기 좋아요",
"카페 같은 분위기에요", "방문객이 많아요", "공간이 넓어요", "깨끗해요", "바비큐 해먹기 좋아요", "그늘이 많아요", "물이 따뜻해요", "수심이 다양해요", "물이 깨끗해요", "책 읽기 쾌적해요",
"대화하기 좋아요", "집중하기 좋아요", "조용히 쉬기 좋아요", "원하는 책을 찾기 쉬워요", "오래 머무르기 좋아요", "좌석이 편해요", "최신 장비를 사용해요", "행사 상품이 다양해요", "분위기가 편안해요",
"매장이 청결해요", "매장이 넓어요", "코스가 길어요", "코스가 변별력 있어요", "혼밥하기 좋아요", "필드 상태가 좋아요", "클럽하우스가 잘 되어있어요", "붐비지 않아요", "대기시간이 짧아요", "소수정예에요",
"물놀이하기 좋아요", "파티하기 좋아요", "특이한 찜질방이 있어요", "고기 질이 좋아요", "먹거리가 풍부해요", "그늘집이 잘 되어있어요", "세트장 구성이 다양해요", "다양하게 연출하기 좋아요", "초보자에게도 적합해요",
"신기한 식물이 많아요", "피크닉하기 좋아요", "슬로프가 길어요", "아이와 가기 좋아요", "유익해요", "물놀이하기 좋아요", "컨셉이 독특해요", "사진 컨셉이 다양해요", "특별한 날 가기 좋아요",
"재료가 신선해요", "뷰가 좋아요", "사진이 잘 나와요", "야경이 멋져요", "경관이 독특해요", "자연 경관이 좋아요", "야외 공간이 멋져요", "채광이 좋아요", "인테리어가 멋져요", "독특한 디자인이 많아요",
"아기자기해요", "고급스러워요", "예쁜 소품이 많아요", "트렌디해요", "아늑해요", "카페 같은 분위기에요", "소품이 다양해요", "키덜트족에게 좋아요", "특색 있는 제품이 많아요", "신상품이 많아요",
"사이즈가 다양해요", "옷이 예뻐요", "옷 관리가 잘 되어있어요", "옷이 다양해요", "독특한 의상이 많아요", "좋은 제품을 사용해요", "과채가 신선해요", "종류가 다양해요", "베스트셀러가 많아요",
"신간이 빨리 들어와요", "상품이 다양해요", "선물하기 좋아요", "트렌디한 상품이 많아요", "맞춤 제작을 잘해요", "예쁜 아기 의상이 많아요", "독특한 책이 많아요"],

"편의성 및 접근성" : ["편의시설이 잘 되어있어요", "대중교통이 편해요", "주차하기 편해요" , "마트 이용이 편해요","마트 이용이 편해요","셔틀버스가 잘 되어있어요",
               "근처에 갈 곳이 많아요", "대중교통이 편해요", "근처에 식당이 많아요" ,"산책로가 잘 되어있어요", '배달 시스템이 편리해요'],

"활동(프로그램)" : ["전시 구성이 알차요", "볼거리가 많아요", "체험 프로그램이 다양해요", "놀이기구가 다양해요", "공연이 재밌어요", "강습 받기 좋아요", "책 종류가 다양해요", "놀거리가 많아요", "야외에서 놀기 좋아요",
"커플로 맞추기 좋아요", "즐길 거리가 많아요", "프로그램이 다양해요", "재미있는 테마가 많아요", "스토리가 탄탄해요", "문제가 신선해요", "전시 테마가 재밌어요", "야시장이 잘 되어있어요"],

"서비스" : ["피팅이 자유로워요", "맞춤 지도를 잘해줘요", "스타일 추천을 잘해줘요", "자연스럽게 연출해줘요", "친절해요", "안전하게 관리해요", "추천을 잘해줘요", "예약이 편리해요", "설명이 잘 되어있어요",
"상담이 자세해요", "손이 빨라요", "관리법을 잘 알려줘요", "맞춤 케어를 잘해줘요", "과도한 권유가 없어요", "관리 효과가 좋아요", "가격 안내가 명확해요", "대화가 즐거워요", "필요한 대화만 오가요",
"서비스가 좋아요", "픽업서비스가 편해요", "A/S가 세심해요", "설명이 자세해요", "배송 시스템이 편리해요", "할인/적립을 잘 챙겨줘요", "맞춤 제작을 잘해줘요", "유익해요", "선생님이 열정적이에요",
"수업이 체계적이에요", "세신사의 실력이 좋아요", "학생과 소통을 잘해요", "포장이 정성스러워요", "주문제작을 잘해줘요", "보정을 꼼꼼하게 해줘요", "캐디의 진행이 매끄러워요", "예약 시간을 잘 지켜요",
"거리 측정을 잘해줘요", "검안이 꼼꼼해요", "시술이 꼼꼼해요", "원하는 스타일로 잘해줘요", "자연스러워요", "선생님 실력이 좋아요"],

"가격" : ["가격이 합리적이에요", "가성비가 좋아요", "품질이 좋아요", "비싼 만큼 가치있어요"]
}

In [90]:
info_tour = info[info['Category'] == '관광']

# df에 속성을 업로
def update_categories(info_tour, category_map_tour):
    for category, keywords in category_map_tour.items():
        for keyword in keywords:
            info_tour.loc[info_tour['Good_Point'].str.contains(keyword), 'Category_Map'] = category
    return info_tour

info_tour = update_categories(info_tour, category_map_tour)
info_tour

C:\Users\82108\AppData\Local\Temp\ipykernel_25996\3457364920.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  info_tour.loc[info_tour['Good_Point'].str.contains(keyword), 'Category_Map'] = category

,Attraction,type,Good_Point,Selected_People,Category,Address,Participants,Category_Map
0,104고지전적비,history,사진이 잘 나와요,91.0,관광,서울특별시 서대문구 연희동 산100-1,203,시설 및 분위기
1,104고지전적비,history,볼거리가 많아요,58.0,관광,서울특별시 서대문구 연희동 산100-1,203,활동(프로그램)
2,104고지전적비,history,붐비지 않아요,40.0,관광,서울특별시 서대문구 연희동 산100-1,203,시설 및 분위기
3,104고지전적비,history,가격이 합리적이에요,37.0,관광,서울특별시 서대문구 연희동 산100-1,203,가격
4,104고지전적비,history,관리가 잘 되어있어요,31.0,관광,서울특별시 서대문구 연희동 산100-1,203,시설 및 분위기
...,...,...,...,...,...,...,...,...
4846,POOM아트박스 (신촌점),shop_etc,예쁜 소품이 많아요,13.0,관광,서울특별시 서대문구 명물길 23,898,시설 및 분위기
4847,POOM아트박스 (신촌점),shop_etc,주차하기 편해요,12.0,관광,서울특별시 서대문구 명물길 23,898,편의성 및 접근성
4848,POOM아트박스 (신촌점),shop_etc,신상품이 많아요,6.0,관광,서울특별시 서대문구 명물길 23,898,시설 및 분위기
4849,POOM아트박스 (신촌점),shop_etc,선물하기 좋아요,5.0,관광,서울특별시 서대문구 명물길 23,898,시설 및 분위기
4850,POOM아트박스 (신촌점),shop_etc,독특한 디자인이 많아요,4.0,관광,서울특별시 서대문구 명물길 23,898,시설 및 분위기

In [91]:
info_tour = info_tour[info_tour['Category_Map'] != 'nan']

In [92]:
info_tour = info_tour.dropna(axis=0)

In [93]:
category_map = pd.concat([info_tour,info_food], axis = 0)
category_map

,Attraction,type,Good_Point,Selected_People,Category,Address,Participants,Category_Map
0,104고지전적비,history,사진이 잘 나와요,91.0,관광,서울특별시 서대문구 연희동 산100-1,203,시설 및 분위기
1,104고지전적비,history,볼거리가 많아요,58.0,관광,서울특별시 서대문구 연희동 산100-1,203,활동(프로그램)
2,104고지전적비,history,붐비지 않아요,40.0,관광,서울특별시 서대문구 연희동 산100-1,203,시설 및 분위기
3,104고지전적비,history,가격이 합리적이에요,37.0,관광,서울특별시 서대문구 연희동 산100-1,203,가격
4,104고지전적비,history,관리가 잘 되어있어요,31.0,관광,서울특별시 서대문구 연희동 산100-1,203,시설 및 분위기
...,...,...,...,...,...,...,...,...
15517,h450,west,아늑해요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,시설 및 분위기
15518,h450,west,메뉴 구성이 알차요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,가격 및 가치
15519,h450,west,건강한 맛이에요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,음식의 속성
15520,h450,west,음료가 맛있어요,1.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,음식의 속성
15521,h450,west,음식이 빨리 나와요,1.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,서비스

In [94]:
info[:1]

,Attraction,type,Good_Point,Selected_People,Category,Address,Participants
0,104고지전적비,history,사진이 잘 나와요,91.0,관광,서울특별시 서대문구 연희동 산100-1,203

In [95]:
category_map = category_map[["Attraction","Good_Point","Category_Map"]]
category_map[:]

      Attraction   Good_Point Category_Map
0       104고지전적비    사진이 잘 나와요     시설 및 분위기
1       104고지전적비     볼거리가 많아요     활동(프로그램)
2       104고지전적비      붐비지 않아요     시설 및 분위기
3       104고지전적비   가격이 합리적이에요           가격
4       104고지전적비  관리가 잘 되어있어요     시설 및 분위기
...          ...          ...          ...
15517       h450         아늑해요     시설 및 분위기
15518       h450   메뉴 구성이 알차요      가격 및 가치
15519       h450     건강한 맛이에요       음식의 속성
15520       h450     음료가 맛있어요       음식의 속성
15521       h450   음식이 빨리 나와요          서비스

[15510 rows x 3 columns]

In [96]:
all = pd.merge(info, category_map, how = 'left')
all

,Attraction,type,Good_Point,Selected_People,Category,Address,Participants,Category_Map
0,104고지전적비,history,사진이 잘 나와요,91.0,관광,서울특별시 서대문구 연희동 산100-1,203,시설 및 분위기
1,104고지전적비,history,볼거리가 많아요,58.0,관광,서울특별시 서대문구 연희동 산100-1,203,활동(프로그램)
2,104고지전적비,history,붐비지 않아요,40.0,관광,서울특별시 서대문구 연희동 산100-1,203,시설 및 분위기
3,104고지전적비,history,가격이 합리적이에요,37.0,관광,서울특별시 서대문구 연희동 산100-1,203,가격
4,104고지전적비,history,관리가 잘 되어있어요,31.0,관광,서울특별시 서대문구 연희동 산100-1,203,시설 및 분위기
...,...,...,...,...,...,...,...,...
16879,h450,west,아늑해요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,시설 및 분위기
16880,h450,west,메뉴 구성이 알차요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,가격 및 가치
16881,h450,west,건강한 맛이에요,2.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,음식의 속성
16882,h450,west,음료가 맛있어요,1.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,음식의 속성
16883,h450,west,음식이 빨리 나와요,1.0,음식,서울특별시 강남구 압구정로29길 21 문화센터 건물 1층,260,서비스

In [97]:
all.columns

Index(['Attraction', 'type', 'Good_Point', 'Selected_People', 'Category',
       'Address', 'Participants', 'Category_Map'],
      dtype='object')

In [98]:
all=all[['Attraction', 'Category', 'type', "Category_Map", "Good_Point", "Selected_People", "Participants"]]

In [99]:
all['Attraction'].nunique()

785

In [100]:
all[:]

,Attraction,Category,type,Category_Map,Good_Point,Selected_People,Participants
0,104고지전적비,관광,history,시설 및 분위기,사진이 잘 나와요,91.0,203
1,104고지전적비,관광,history,활동(프로그램),볼거리가 많아요,58.0,203
2,104고지전적비,관광,history,시설 및 분위기,붐비지 않아요,40.0,203
3,104고지전적비,관광,history,가격,가격이 합리적이에요,37.0,203
4,104고지전적비,관광,history,시설 및 분위기,관리가 잘 되어있어요,31.0,203
...,...,...,...,...,...,...,...
16879,h450,음식,west,시설 및 분위기,아늑해요,2.0,260
16880,h450,음식,west,가격 및 가치,메뉴 구성이 알차요,2.0,260
16881,h450,음식,west,음식의 속성,건강한 맛이에요,2.0,260
16882,h450,음식,west,음식의 속성,음료가 맛있어요,1.0,260
16883,h450,음식,west,서비스,음식이 빨리 나와요,1.0,260

In [101]:
# '/'가 있는 행과 없는 행 구분
has_slash = all['type'].str.contains('/')

# '/'가 있는 행 처리
new_categories = all.loc[has_slash, 'type'].str.split('/', expand=True)
all.loc[has_slash, 'type'] = new_categories[0]
all['type2'] = new_categories[1]

# '/'가 없는 행 처리 (기존 값 유지)
all.loc[~has_slash, 'type2'] = all.loc[~has_slash, 'type']

# 결과 출력
all

,Attraction,Category,type,Category_Map,Good_Point,Selected_People,Participants,type2
0,104고지전적비,관광,history,시설 및 분위기,사진이 잘 나와요,91.0,203,history
1,104고지전적비,관광,history,활동(프로그램),볼거리가 많아요,58.0,203,history
2,104고지전적비,관광,history,시설 및 분위기,붐비지 않아요,40.0,203,history
3,104고지전적비,관광,history,가격,가격이 합리적이에요,37.0,203,history
4,104고지전적비,관광,history,시설 및 분위기,관리가 잘 되어있어요,31.0,203,history
...,...,...,...,...,...,...,...,...
16879,h450,음식,west,시설 및 분위기,아늑해요,2.0,260,west
16880,h450,음식,west,가격 및 가치,메뉴 구성이 알차요,2.0,260,west
16881,h450,음식,west,음식의 속성,건강한 맛이에요,2.0,260,west
16882,h450,음식,west,음식의 속성,음료가 맛있어요,1.0,260,west
16883,h450,음식,west,서비스,음식이 빨리 나와요,1.0,260,west

In [102]:
all = all[['Attraction', 'Category', 'type', 'type2', 'Category_Map', 'Good_Point', 'Selected_People', 'Participants']]

In [103]:
all

,Attraction,Category,type,type2,Category_Map,Good_Point,Selected_People,Participants
0,104고지전적비,관광,history,history,시설 및 분위기,사진이 잘 나와요,91.0,203
1,104고지전적비,관광,history,history,활동(프로그램),볼거리가 많아요,58.0,203
2,104고지전적비,관광,history,history,시설 및 분위기,붐비지 않아요,40.0,203
3,104고지전적비,관광,history,history,가격,가격이 합리적이에요,37.0,203
4,104고지전적비,관광,history,history,시설 및 분위기,관리가 잘 되어있어요,31.0,203
...,...,...,...,...,...,...,...,...
16879,h450,음식,west,west,시설 및 분위기,아늑해요,2.0,260
16880,h450,음식,west,west,가격 및 가치,메뉴 구성이 알차요,2.0,260
16881,h450,음식,west,west,음식의 속성,건강한 맛이에요,2.0,260
16882,h450,음식,west,west,음식의 속성,음료가 맛있어요,1.0,260
16883,h450,음식,west,west,서비스,음식이 빨리 나와요,1.0,260

In [104]:
all.columns

Index(['Attraction', 'Category', 'type', 'type2', 'Category_Map', 'Good_Point',
       'Selected_People', 'Participants'],
      dtype='object')

In [105]:
total_info.columns

Index(['Attraction', 'Good_Point', 'Selected_People', 'Category', 'Address',
       'Participants'],
      dtype='object')

In [106]:
total_info['Attraction']

0        동대문역사문화공원
1        동대문역사문화공원
2        동대문역사문화공원
3        동대문역사문화공원
4        동대문역사문화공원
           ...
17122         h450
17123         h450
17124         h450
17125         h450
17126         h450
Name: Attraction, Length: 15616, dtype: object

In [107]:
# total_info의 'Attraction'을 기준으로 all의 'Attraction'을 변경
# 먼저 total_info와 all을 'Attraction' 열을 기준으로 병합
merged_df = pd.merge(total_info, all, on='Attraction', suffixes=('_total', '_all'))

# 필요한 열만 선택하여 최종 결과를 얻음
result = merged_df[['Attraction', 'Category_all', 'type', 'type2', 'Category_Map', 'Good_Point_all', 'Selected_People_all', 'Participants_all']]
result.columns = ['Attraction', 'Category', 'type', 'type2', 'Category_Map', 'Good_Point', 'Selected_People', 'Participants']

# 결과 출력
df = pd.DataFrame(result)

In [108]:
df['Attraction'].nunique()

785

In [109]:
all['Attraction'].nunique()

785

In [110]:
df.to_csv('통합_데이터셋_투어속성변경.csv')